<?php

namespace Threek;

/**
 * Generated by the WordPress Meta Box Generator
 * https://jeremyhixon.com/tool/wordpress-meta-box-generator/
 * 
 * Retrieving the values:
 * Author = get_post_meta( get_the_ID(), 'custom_checked_byauthor', true )
 */
class CheckedBy {
	/**
	 * where to show
	 */
	private array $post_type = [
		'post'
	];

	/**
	 * position
	 */
	private $context = 'side';

	/**
	 * title for Metabox
	 */
    private $title = 'Checked by';

	/**
	 * high, core, default, low
	 */
	private $priority = 'high';

	/**
	 * id, name for select, input ...
	 */
    private $field_id = 'custom_checked_by_author';

	public function __construct() {
		add_action( 'add_meta_boxes', [ $this, 'add_meta_boxes' ] );
		add_action( 'save_post', [ $this, 'save_post' ] );
	}

	public function add_meta_boxes() {
		foreach ( $this->post_type as $screen ) {
			add_meta_box(
				sanitize_title( $this->title ),
				$this->title,
				[ $this, 'add_meta_box_callback' ],
				$screen,
				$this->context,
				$this->priority
			);
		}
	}

	/**
	 * save metabox value
	 */
	public function save_post( $post_id ) {
		if ( isset( $_POST[ $this->field_id ] ) ) {
			update_post_meta( 
				$post_id, 
				$this->field_id, 
				sanitize_text_field( $_POST[ $this->field_id ] ) 
			);
		}
	}

	public function add_meta_box_callback() {
		$this->fields_div();
	}

	private function fields_div() {
		$authors = get_users();
		?>

		<select name="<?php echo $this->field_id; ?>" id="<?php echo $this->field_id; ?>" autocomplete="off">
		<option value="0">- - - - - - - - - - - -</option>
		<?php foreach( $authors as $author ): ?>
			<option value="<?php echo $author->ID; ?>" <?php echo ( (int)$author->ID === (int)$this->value( $this->field_id ) ? 'selected' : '' ); ?>>
				<?php echo $author->display_name; ?>
			</option>
		<?php endforeach; ?>
		</select>

		<?php
	}

	/**
	 * get current value
	 * @param $field_id
	 */
	private function value( $field_id ) {
		global $post;
		if ( metadata_exists( 'post', $post->ID, $field_id ) ) {
			$value = get_post_meta( $post->ID, $field_id, true );
		} else {
			return '';
		}

		return $value;
	}

}